{% set name = "dingo-gw" %}
{% set version = "0.9.7" %}

{% set python_min = "3.10" %}
{% set python_max = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 79063e6e181d972cc826808e23c6e1457eeb1eb94f386e0a191d1e509c0012d3
  patches:
    - no-lalsuite.patch

build:
  entry_points:
    - dingo_append_training_stage = dingo.gw.training:append_stage
    - dingo_build_svd = dingo.gw.dataset.utils:build_svd_cli
    - dingo_estimate_psds = dingo.gw.noise.asd_estimation:download_and_estimate_cli
    - dingo_generate_asd_dataset = dingo.gw.noise.generate_dataset:generate_dataset
    - dingo_generate_dataset = dingo.gw.dataset.generate_dataset:main
    - dingo_generate_dataset_dag = dingo.gw.dataset.generate_dataset_dag:main
    - dingo_generate_synthetic_asd_dataset = dingo.gw.noise.synthetic.generate_dataset:main
    - dingo_ls = dingo.gw.ls_cli:ls
    - dingo_pipe = dingo.pipe.main:main
    - dingo_pipe_importance_sampling = dingo.pipe.importance_sampling:main
    - dingo_pipe_generation = dingo.pipe.data_generation:main
    - dingo_pipe_plot = dingo.pipe.plot:main
    - dingo_pipe_pp_test = dingo.pipe.pp_test:main
    - dingo_pipe_sampling = dingo.pipe.sampling:main
    - dingo_pt_to_hdf5 = dingo.core.utils.pt_to_hdf5:main
    - dingo_merge_datasets = dingo.gw.dataset.utils:merge_datasets_cli
    - dingo_merge_asd_datasets = dingo.gw.noise.utils:merge_datasets_cli
    - dingo_result = dingo.pipe.dingo_result:main
    - dingo_train = dingo.gw.training:train_local
    - dingo_train_condor = dingo.gw.training.train_pipeline_condor:train_condor
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >={{ python_min }},<{{ python_max }}
    - setuptools >=62.0
    - setuptools-scm >=6.2
    - pip
  run:
    - astropy-base
    - bilby
    - bilby_pipe
    - configargparse
    - corner
    - glasflow
    - gwpy
    - h5py
    - matplotlib-base
    - numpy
    - pandas
    - pycbc
    - pycondor
    - python >={{ python_min }},<{{ python_max }}
    - python-lal >=7.3.1
    - python-lalsimulation >=5.2.0
    - pytorch
    - pyyaml
    - requests
    - scikit-learn
    - scipy
    - threadpoolctl
    - torchdiffeq
    - torchvision
    - tqdm

test:
  imports:
    - dingo
  commands:
    # - pip check  # Do not run since sxs package causes failure due to dependencies
    - dingo_append_training_stage --help
    - dingo_build_svd --help
    - dingo_estimate_psds --help
    - dingo_generate_asd_dataset --help
    - dingo_generate_dataset --help
    - dingo_generate_dataset_dag --help
    - dingo_generate_synthetic_asd_dataset --help
    - dingo_ls --help
    - dingo_merge_asd_datasets --help
    - dingo_merge_datasets --help
    - dingo_pipe --help
    - dingo_pipe_generation --help
    - dingo_pipe_importance_sampling --help
    - dingo_pipe_plot --help
    - dingo_pipe_sampling --help
    - dingo_pt_to_hdf5 --help
    - dingo_result --help
    - dingo_train --help
    - dingo_train_condor --help
  requires:
    - pip
    # forcibly install uptodate xarray so that pip check doesn't choke on arviz
    - xarray >=0.21.0
    - python >={{ python_min }},<{{ python_max }}

about:
  home: https://github.com/dingo-gw/dingo
  summary: Deep inference for gravitational-wave observations
  description: |
    Dingo is a Python program for analyzing gravitational wave data using
    neural posterior estimation. It dramatically speeds up inference of
    astrophysical source parameters from data measured at gravitational-wave
    observatories. Dingo aims to enable the routine use of the most
    advanced theoretical models in analyzing data, to make rapid predictions
    for multi-messenger counterparts, and to do so in the context of
    sensitive detectors with high event rates.
  license: MIT
  license_file: LICENSE
  doc_url: https://dingo-gw.readthedocs.io/
  dev_url: https://github.com/dingo-gw/dingo

extra:
  recipe-maintainers:
    - stephengreen
    - max-dax
